apiVersion: v1
kind: Service
metadata:
  name: policy-webhook-service
  namespace: policy-system
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app: policy-operator