apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: resource-policy-webhook
webhooks:
  - name: resource-policy.policies.example.com
    clientConfig:
      service:
        name: policy-webhook-service
        namespace: policy-system
        path: "/validate-deployment"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdHZ0F3SUJBZ0lVUnhpaWlmZkp6MjhZaHRPRHhhZUxvWWdZbmNvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF3d1JjRzlzYVdONUxYZGxZbWh2YjJzdFkyRXdIaGNOTWpVd09ESTRNVE14T0RJMwpXaGNOTWpZd09ESTRNVE14T0RJM1dqQWNNUm93R0FZRFZRUUREQkZ3YjJ4cFkza3RkMlZpYUc5dmF5MWpZVENDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1NUbEt5WHV1UUI5TjJndFZ4WFVza20KVnNIMDBkSmx0bjZEaDEwREpBdXFwQjJET2dlVXp4M0h4SVJ2UFRwTUtWNGdYN3hva2FwL292YU51eVdtRmE2cApaUjBORHRGVGdZemoybU0wVEpwRVhjSXZQcnBXM1ZVaUM3aEVsT1J0VmcwQlBpNHY1dng5VytnOVFpVytjSTUzClBSSXpzdTZsZzE0YXdPRENoTkREa0lRK2pDdUpGdWszTlEwQUlrNUpvZjNMK0U1d29OZlBmK2YyK09TalFQVkcKYWhrWmFCeElMMUZ4MHVSdEpVcFlhZXQzeW5zRFNpcHBhTTJ6WkdEbUJZZWVrZzM2ZUN2VzVWRkNHbGRyRUNGRgpacENMSnVyQnBqYXNXbUd1ZXNPNUkrL3pWczVzOXJMTHhlb1cyeVdMcVdvUjdoREV4MGxmL28wNXFTQXZNaWtDCkF3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZML2x3cVEzczhHamU0ZmMwZVIwZDRCMThla01NQjhHQTFVZEl3UVkKTUJhQUZML2x3cVEzczhHamU0ZmMwZVIwZDRCMThla01NQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQURqU3pKN0RoSGY2OW1iM20rNTc2WHVGWEU2RHhuNlJobndFUk9pRWJraTZxMUZXCndmV0p6NHhlNkxHZlZKWFI0SG12UE4yODBmcCsrVGJtcDBxMmdvcGRoRVBGaFRmY1lJWTRXS3hoTjNyVk5taEkKUTlrcmw1T25yZVcvWmh0djU5cWxOOVYzN2ZWcGYxT3h2SGtQRjZHRGh6SWV0OFgrN2VVUWJRczJOS2NRMkNGVgpFSUhpanlWbVJyNjV0cHo2ODlyb05CNlBwdHJXOHhMNDB1Z0xJZ2hOODByM0ZEa3p4QjExc0FJM05qcUtneDltCm1WOUtYbWFNbFhnWkcrTnhSNFFQbmYrYWtKNHBVckRra2FYQ0F5VEdFSVJRRzUwdVAxbCtCaHhCSm81Q0pzaU8KclB0OGlpbEFqUjNlQmRLVXQxTjRtL0ZtVTJkK2xxa0JZT2pGTzF3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
    sideEffects: None
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
