apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: nginx:latest
        resources:
          limits:
            memory: "1Gi"     # Więcej niż limit w polityce (512Mi) - powinno być odrzucone
            cpu: "1000m"      # Więcej niż limit w polityce (500m) - powinno być odrzucone
          requests:
            memory: "128Mi"
            cpu: "100m"